// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	models "github.com/leyl1ne/rest-api-parser/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ArtistGetterAll is an autogenerated mock type for the ArtistGetterAll type
type ArtistGetterAll struct {
	mock.Mock
}

// GetAllArtist provides a mock function with given fields:
func (_m *ArtistGetterAll) GetAllArtist() ([]models.Artist, error) {
	ret := _m.Called()

	var r0 []models.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Artist, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Artist); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Artist)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewArtistGetterAll interface {
	mock.TestingT
	Cleanup(func())
}

// NewArtistGetterAll creates a new instance of ArtistGetterAll. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewArtistGetterAll(t mockConstructorTestingTNewArtistGetterAll) *ArtistGetterAll {
	mock := &ArtistGetterAll{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
