// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ArtistDeleter is an autogenerated mock type for the ArtistDeleter type
type ArtistDeleter struct {
	mock.Mock
}

// DeleteArtist provides a mock function with given fields: id
func (_m *ArtistDeleter) DeleteArtist(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewArtistDeleter interface {
	mock.TestingT
	Cleanup(func())
}

// NewArtistDeleter creates a new instance of ArtistDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewArtistDeleter(t mockConstructorTestingTNewArtistDeleter) *ArtistDeleter {
	mock := &ArtistDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
