// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	models "github.com/leyl1ne/rest-api-parser/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ArtistGetter is an autogenerated mock type for the ArtistGetter type
type ArtistGetter struct {
	mock.Mock
}

// GetArtist provides a mock function with given fields: id
func (_m *ArtistGetter) GetArtist(id int) (models.Artist, error) {
	ret := _m.Called(id)

	var r0 models.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Artist, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Artist); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Artist)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewArtistGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewArtistGetter creates a new instance of ArtistGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewArtistGetter(t mockConstructorTestingTNewArtistGetter) *ArtistGetter {
	mock := &ArtistGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
