// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	models "github.com/leyl1ne/rest-api-parser/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ArtistSaver is an autogenerated mock type for the ArtistSaver type
type ArtistSaver struct {
	mock.Mock
}

// SaveArtist provides a mock function with given fields: artist
func (_m *ArtistSaver) SaveArtist(artist models.Artist) (int64, error) {
	ret := _m.Called(artist)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Artist) (int64, error)); ok {
		return rf(artist)
	}
	if rf, ok := ret.Get(0).(func(models.Artist) int64); ok {
		r0 = rf(artist)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(models.Artist) error); ok {
		r1 = rf(artist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewArtistSaver interface {
	mock.TestingT
	Cleanup(func())
}

// NewArtistSaver creates a new instance of ArtistSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewArtistSaver(t mockConstructorTestingTNewArtistSaver) *ArtistSaver {
	mock := &ArtistSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
